language: android


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

env:
  global:
  - ADB_INSTALL_TIMEOUT=20    #Time out to 20 mins
  - ANDROID_EMULATOR_API_LEVEL=24
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  #- GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2868M -XX:MaxPermSize=2868m"

android:
  update_sdk: true
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-$ANDROID_EMULATOR_API_LEVEL
    - android-25
    - extra-android-m2repository

    # The android emulator image
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
  - android-sdk-license-.+
  - '.+'

branches:
  except:
    - gh-pages

notifications:
  email: false

# Container builds fail due to memory let's try non container
sudo: true

cache:
  directories:
    - $HOME/.m2

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &

script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - curl -o file.apk "https://dl.bintray.com/linkedin/maven/com/linkedin/testbutler/test-butler-app/1.2.0/test-butler-app-1.2.0.apk" && adb install file.apk
  - adb shell input tap 400 933 & #Hopefully it will close that annoying "Process system isn't responding" dialog that fails the tests
  - ./gradlew jacocoTestReport -PdisablePreDex --continue --stacktrace
after_success:
  - ./gradlew coveralls -PdisablePreDex --stacktrace

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
  - ./imgurbash.sh screen.png
