[versions]
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-arch-core-testing = "2.2.0"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.16.0"
androidx-core-splashscreen = "1.0.1"
androidx-datastore = "1.1.7"
androidx-fragment = "1.8.8"
androidx-lifecycle = "2.9.1"
androidx-media3 = "1.7.1"
androidx-paging-runtime-ktx = "3.3.6"
androidx-preference-ktx = "1.2.1"
androidx-recyclerview = "1.4.0"
androidx-room = "2.7.2"
androidx-test-core = "1.6.1"
androidx-test-espresso = "3.6.1"
androidx-test-junit = "1.2.1"
androidx-test-runner = "1.6.2"
androidx-test-truth = "1.6.0"
androidx-viewpager2 = "1.1.0"
androidx-swiperefreshlayout = "1.1.0"
coil = "3.2.0"
desugar = "2.1.5"
firebaseBom = "33.16.0"
google-material = "1.12.0"
gradlePlugin-agp = "8.11.0"
gradlePlugin-crashlytics = "3.0.4"
gradlePlugin-detekt = "1.23.8"
gradlePlugin-gms = "4.4.3"
gradlePlugin-kotlinter = "5.1.1"
gradlePlugin-kover = "0.9.1"
gradlePlugin-ksp = "2.2.0-2.0.2"
gradlePlugin-protobuf = "0.9.5"
gradlePlugin-versionCatalog = "1.0.0"
gradlePlugin-versionsBenManes = "0.52.0"
koin = "4.1.0"
kotlin = "2.2.0"
kotlinCoroutines = "1.10.2"
mockk = "1.14.4"
protobuf = "4.31.1"
robolectric = "4.15.1"
squareup-leakcanary = "2.14"
squareup-moshi = "1.15.2"
squareup-okhttp = "4.12.0"
squareup-okio = "3.13.0"
timber = "5.0.1"
truth = "1.4.4"
turbine = "1.2.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core-testing" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "androidx-media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidx-media3" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging-runtime-ktx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging-runtime-ktx" }
androidx-paging-testing = { module = "androidx.paging:paging-testing", version.ref = "androidx-paging-runtime-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-truth" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref= "androidx-swiperefreshlayout"}
coilKt-coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coilKt-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
com-android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-perf-ktx = { module = "com.google.firebase:firebase-perf-ktx" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "squareup-moshi" }
squareup-moshi-lib = { module = "com.squareup.moshi:moshi", version.ref = "squareup-moshi" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "squareup-okhttp" }
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "squareup-okio" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
androidx-lifecycle = [
    "androidx-lifecycle-common",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-ktx",
]
androidx-media3 = [
    "androidx-media3-common-ktx",
    "androidx-media3-session"
]
androidx-room = [
    "androidx-room-ktx",
    "androidx-room-paging",
    "androidx-room-runtime",
]
androidx-test-espresso = [
    "androidx-test-espresso-contrib",
    "androidx-test-espresso-core",
    "androidx-test-espresso-intents",
]
coil = [
    "coilKt-coil",
    "coilKt-network-okhttp",
]
coroutines = [
    "kotlin-coroutines-android",
    "kotlin-coroutines-core",
]
google-firebase = [
    "google-firebase-analytics-ktx",
    "google-firebase-crashlytics-ktx",
    "google-firebase-perf-ktx",
]
koin = [
    "koin-android",
    "koin-workmanager",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin-agp" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin-agp" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradlePlugin-crashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "gradlePlugin-detekt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gradlePlugin-gms" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradlePlugin-kotlinter" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "gradlePlugin-kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "gradlePlugin-ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "gradlePlugin-protobuf" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradlePlugin-versionCatalog" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "gradlePlugin-versionsBenManes" }
